"""
TimeStone AI — Claude AI Integration

Uses Anthropic Claude for intelligent scenario generation, narrative
synthesis, and strategic reasoning. This is what makes TimeStone an
AI-native product, not just a simulation tool.

Capabilities:
1. Scenario Generation — Claude proposes transformation scenarios
   based on company genome, industry context, and market conditions
2. Narrative Synthesis — translates statistical outputs into
   compelling executive narratives
3. Risk Interpretation — explains tail risks in business language
4. Strategic Reasoning — synthesizes insights into coherent strategy
5. Counterfactual Explanation — explains "what would have happened if"
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

try:
    from anthropic import Anthropic
except ImportError:
    Anthropic = None


SYSTEM_PROMPT = """You are TimeStone AI's strategic intelligence engine. You analyze
business transformation scenarios for enterprises using causal graph analysis,
Monte Carlo simulation, and company genome profiling.

Your role is to:
1. Generate creative but realistic transformation scenarios
2. Synthesize statistical results into executive-grade narratives
3. Identify non-obvious risks and opportunities
4. Explain complex causal dynamics in business language
5. Provide actionable strategic recommendations

Always be specific, quantitative, and actionable. Never be vague.
Reference the actual numbers from the analysis."""


@dataclass
class GeneratedScenario:
    """A transformation scenario generated by Claude."""
    name: str
    description: str
    transformation_type: str
    expected_revenue_increase: float
    expected_cost_reduction: float
    investment_required: float
    implementation_time_months: int
    risk_level: str
    rationale: str
    prerequisites: List[str]
    key_risks: List[str]


class ClaudeIntegration:
    """
    Anthropic Claude integration for intelligent analysis.

    Uses Claude for creative scenario generation, narrative synthesis,
    and strategic reasoning — tasks where LLMs excel beyond what
    pure statistical engines can deliver.
    """

    def __init__(self, api_key: Optional[str] = None, model: str = "claude-sonnet-4-20250514"):
        self.api_key = api_key or os.getenv("ANTHROPIC_API_KEY")
        self.model = model
        self._client: Optional[Any] = None

    @property
    def client(self):
        if self._client is None:
            if Anthropic is None:
                raise ImportError("anthropic package not installed. Run: pip install anthropic")
            if not self.api_key:
                raise ValueError("ANTHROPIC_API_KEY not set")
            self._client = Anthropic(api_key=self.api_key)
        return self._client

    @property
    def available(self) -> bool:
        return Anthropic is not None and bool(self.api_key)

    def generate_scenarios(
        self,
        company_name: str,
        industry: str,
        genome_summary: Dict,
        current_challenges: List[str],
        budget_range: tuple = (1_000_000, 50_000_000),
        num_scenarios: int = 10,
    ) -> List[GeneratedScenario]:
        """
        Use Claude to generate creative transformation scenarios
        tailored to this specific company's genome and context.
        """
        prompt = f"""Analyze this company and generate {num_scenarios} transformation scenarios.

COMPANY: {company_name}
INDUSTRY: {industry}
BUDGET RANGE: ${budget_range[0]:,.0f} - ${budget_range[1]:,.0f}

COMPANY GENOME (capability scores, 0-1 scale):
{json.dumps(genome_summary, indent=2)}

CURRENT CHALLENGES:
{chr(10).join(f'- {c}' for c in current_challenges)}

Generate exactly {num_scenarios} transformation scenarios. For each scenario, respond with a JSON array where each item has:
- name: concise scenario title
- description: 2-3 sentence description
- transformation_type: one of [digital_transformation, pricing_optimization, operational_efficiency, process_automation, market_expansion, product_innovation, customer_experience, supply_chain]
- expected_revenue_increase: decimal (e.g., 0.15 for 15%)
- expected_cost_reduction: decimal
- investment_required: number in USD
- implementation_time_months: integer
- risk_level: "low", "medium", or "high"
- rationale: why this scenario fits this company's genome
- prerequisites: list of 2-3 things needed first
- key_risks: list of 2-3 main risks

Focus on scenarios that:
1. Address the company's capability GAPS (low genome scores)
2. Leverage the company's STRENGTHS (high genome scores)
3. Are realistic given the budget and industry
4. Include a mix of quick wins and transformational bets

Return ONLY the JSON array, no other text."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=4096,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        text = response.content[0].text.strip()
        # Extract JSON from response
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]

        scenarios_data = json.loads(text)

        return [
            GeneratedScenario(
                name=s["name"],
                description=s["description"],
                transformation_type=s["transformation_type"],
                expected_revenue_increase=s["expected_revenue_increase"],
                expected_cost_reduction=s["expected_cost_reduction"],
                investment_required=s["investment_required"],
                implementation_time_months=s["implementation_time_months"],
                risk_level=s["risk_level"],
                rationale=s.get("rationale", ""),
                prerequisites=s.get("prerequisites", []),
                key_risks=s.get("key_risks", []),
            )
            for s in scenarios_data
        ]

    def synthesize_narrative(
        self,
        company_name: str,
        simulation_results: List[Dict],
        insights: List[Dict],
        recommendations: List[Dict],
        genome_readiness: Dict,
    ) -> Dict[str, str]:
        """
        Generate an executive-grade narrative from simulation results.
        Returns sections for a board presentation.
        """
        prompt = f"""You are preparing a board-level strategy presentation for {company_name}.

SIMULATION RESULTS (top 5 scenarios by Sharpe ratio):
{json.dumps(simulation_results[:5], indent=2)}

KEY INSIGHTS:
{json.dumps(insights[:5], indent=2)}

STRATEGIC RECOMMENDATIONS:
{json.dumps(recommendations[:3], indent=2)}

TRANSFORMATION READINESS:
{json.dumps(genome_readiness, indent=2)}

Generate a structured executive narrative with these exact sections (return as JSON):
- "executive_headline": one powerful sentence (max 20 words)
- "situation_assessment": 2-3 sentences on current state and market context
- "key_findings": 3-4 bullet points (each 1 sentence)
- "recommended_strategy": 3-4 sentences describing the recommended path
- "expected_outcomes": 2-3 bullet points with specific numbers
- "risk_summary": 2-3 sentences on key risks and mitigations
- "call_to_action": 1-2 sentences on what to do NOW
- "90_day_milestones": 3 specific milestones for the next quarter

Return ONLY the JSON object."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=2048,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        text = response.content[0].text.strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]

        return json.loads(text)

    def explain_causal_dynamics(
        self,
        intervention: str,
        causal_paths: List[Dict],
        trajectory_summary: Dict,
    ) -> str:
        """
        Explain complex causal dynamics in plain business language.
        Used for the "Why does this work?" section of recommendations.
        """
        prompt = f"""Explain the following causal dynamics in clear business language
that a non-technical executive would understand.

INTERVENTION: {intervention}

CAUSAL PATHS (how the intervention propagates):
{json.dumps(causal_paths, indent=2)}

OUTCOME TRAJECTORY (how variables change over 24 months):
{json.dumps(trajectory_summary, indent=2)}

Write a 3-4 paragraph explanation of:
1. What happens when you make this intervention
2. The chain of cause-and-effect (in business terms, not math)
3. Why there are lags (what takes time and why)
4. The key uncertainties and what could go differently

Write in direct, confident language. No hedging. Use specific numbers."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=1024,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        return response.content[0].text.strip()

    def interpret_tail_risk(
        self,
        var_95: float,
        cvar_95: float,
        var_99: float,
        regime_analysis: Dict,
        scenario_name: str,
    ) -> str:
        """
        Translate statistical tail risk metrics into business language.
        """
        prompt = f"""Interpret these tail risk metrics for a non-technical executive.

SCENARIO: {scenario_name}

RISK METRICS:
- Value at Risk (95%): {var_95:.1%} — in the worst 5% of outcomes, losses exceed this
- Conditional VaR (95%): {cvar_95:.1%} — average loss in the worst 5%
- Value at Risk (99%): {var_99:.1%} — worst 1% extreme scenario
- Current market regime: {regime_analysis.get('regime', 'unknown')}
- Regime confidence: {regime_analysis.get('confidence', 0):.0%}

Write 2-3 paragraphs explaining:
1. What this means in practical terms (use dollar amounts if base revenue is $500M)
2. How likely these tail events are and what triggers them
3. What specific actions to take to manage this risk

Be direct. Use concrete dollar amounts. No jargon."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=768,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        return response.content[0].text.strip()

    def generate_transformation_playbook(
        self,
        recommendation: Dict,
        company_genome: Dict,
        industry_knowledge: Dict,
    ) -> Dict[str, Any]:
        """
        Generate a detailed implementation playbook for a recommended
        transformation, including week-by-week actions.
        """
        prompt = f"""Generate a detailed implementation playbook for this transformation.

RECOMMENDATION:
{json.dumps(recommendation, indent=2)}

COMPANY CAPABILITIES:
{json.dumps(company_genome, indent=2)}

INDUSTRY CONTEXT:
{json.dumps(industry_knowledge, indent=2)}

Return a JSON object with:
- "title": playbook title
- "executive_sponsor_brief": 2-sentence summary for the exec sponsor
- "success_metrics": list of 4-5 measurable KPIs with targets
- "phase_1_discover" (weeks 1-4): list of specific actions
- "phase_2_pilot" (weeks 5-12): list of specific actions
- "phase_3_scale" (weeks 13-26): list of specific actions
- "phase_4_optimize" (weeks 27-52): list of specific actions
- "team_structure": roles needed with headcount
- "technology_requirements": list of systems/tools needed
- "governance": cadence of reviews, decision gates, escalation paths
- "risk_triggers": specific conditions that should pause the program
- "budget_allocation": breakdown by phase (percentages)

Be extremely specific. No generic platitudes. Each action should be concrete enough to assign to someone on Monday morning.

Return ONLY the JSON object."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=4096,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        text = response.content[0].text.strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]

        return json.loads(text)
