"""Integration test for PDF executive report generation."""
from pathlib import Path
import pytest

from timestone.application import assess_company, AssessOptions
from timestone.domain.company import Company, CompanyMetrics
from timestone.repositories.case_library import CaseLibraryRepository
from timestone.repositories.results import ResultsRepository


REPO_ROOT = Path(__file__).resolve().parents[2]


def test_assess_generates_pdf(tmp_path):
    twin = Company(
        company_name="PDF Test Co",
        metrics=CompanyMetrics(
            revenue=500_000_000, operating_costs=450_000_000, employees=120_000,
            industry="transportation_rail", geography="Kazakhstan",
            industry_tags=["transportation", "logistics"]))
    case_repo = CaseLibraryRepository(REPO_ROOT / "data" / "case_library.json")
    results_repo = ResultsRepository(runs_dir=tmp_path / "runs")
    opts = AssessOptions(scenario_count=20, iterations=100, random_seed=42)
    report = assess_company(twin, options=opts,
                            case_library_repo=case_repo, results_repo=results_repo)

    run_dirs = list((tmp_path / "runs").iterdir())
    assert len(run_dirs) == 1
    pdf = run_dirs[0] / "report.pdf"
    assert pdf.exists(), "report.pdf must be generated by assess_company"
    # Minimum size sanity: a real PDF is at least a few KB
    assert pdf.stat().st_size > 4000, f"PDF suspiciously small: {pdf.stat().st_size} bytes"
    # Must start with the PDF magic header
    assert pdf.read_bytes().startswith(b"%PDF"), "Output does not look like a valid PDF"


def test_pdf_has_expected_pages(tmp_path):
    """PDF must contain cover + summary + recommendations + methodology + sources."""
    twin = Company(
        company_name="PDF Multi-page Co",
        metrics=CompanyMetrics(
            revenue=500_000_000, operating_costs=450_000_000, employees=120_000,
            industry="transportation_rail", geography="Kazakhstan",
            industry_tags=["transportation", "logistics"]))
    case_repo = CaseLibraryRepository(REPO_ROOT / "data" / "case_library.json")
    results_repo = ResultsRepository(runs_dir=tmp_path / "runs")
    assess_company(twin, options=AssessOptions(scenario_count=20, iterations=100),
                   case_library_repo=case_repo, results_repo=results_repo)
    pdf = list((tmp_path / "runs").iterdir())[0] / "report.pdf"
    raw = pdf.read_bytes()
    # PDF page markers
    page_count = raw.count(b"/Type /Page\n") + raw.count(b"/Type/Page\n")
    # Multi-page sanity: at least 4 pages worth of content
    assert pdf.stat().st_size > 8000, "Real multi-section PDF should be > 8KB"
