"""
TimeStone AI - Interactive Dashboard

Streamlit dashboard for visualizing transformation scenarios
and Monte Carlo simulation results.

Usage:
    streamlit run src/api/dashboard.py
"""

import json
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st


# ---------------------------------------------------------------------------
# Path & data loading
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[4]


def discover_companies() -> dict:
    """Look at every *_twin.json in the repo root and return a {label: {twin, scenarios, results}} map."""
    companies = {}
    for twin_path in sorted(REPO_ROOT.glob("*_twin.json")):
        # Skip files generated by the multi-company generator (those are templates only).
        try:
            with open(twin_path) as f:
                twin = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        name = twin.get("company_name", twin_path.stem)
        # Try to locate matching scenarios + results by simple prefix heuristic
        prefix = twin_path.stem.replace("_twin", "").replace("_digital_twin", "")
        scenarios_path = REPO_ROOT / f"{prefix}_scenarios.json"
        results_path = REPO_ROOT / f"{prefix}_simulation_results.json"
        companies[name] = {
            "twin_path": twin_path,
            "scenarios_path": scenarios_path if scenarios_path.exists() else None,
            "results_path": results_path if results_path.exists() else None,
            "twin": twin,
        }
    # KTZ has weird naming - make sure ktz_digital_twin pairs with ktz_scenarios
    ktz_twin = REPO_ROOT / "ktz_digital_twin.json"
    if ktz_twin.exists():
        with open(ktz_twin) as f:
            twin = json.load(f)
        companies[twin.get("company_name", "KTZ")] = {
            "twin_path": ktz_twin,
            "scenarios_path": REPO_ROOT / "ktz_scenarios.json"
            if (REPO_ROOT / "ktz_scenarios.json").exists() else None,
            "results_path": REPO_ROOT / "ktz_simulation_results.json"
            if (REPO_ROOT / "ktz_simulation_results.json").exists() else None,
            "twin": twin,
        }
    return companies


@st.cache_data
def load_company_data(twin_str: str, scenarios_str: str | None, results_str: str | None):
    """Load company JSON bundle. Strings used so streamlit can cache paths."""
    twin = json.loads(Path(twin_str).read_text())
    scenarios = json.loads(Path(scenarios_str).read_text()) if scenarios_str else None
    results = json.loads(Path(results_str).read_text()) if results_str else None
    return twin, scenarios, results


# ---------------------------------------------------------------------------
# Page setup
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="TimeStone AI",
    page_icon="T",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        font-weight: 900;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0;
    }
    .subtitle {
        font-size: 1.2rem;
        color: #666;
        margin-top: 0;
    }
</style>
""", unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------------
def fmt_pct(x, decimals=1):
    """Format a fractional value (e.g. 0.55) as percentage. Handles None gracefully."""
    if x is None:
        return "-"
    return f"{x * 100:.{decimals}f}%"


def fmt_money(x, scale="auto"):
    """Format a USD value with K/M/B scaling."""
    if x is None:
        return "-"
    abs_x = abs(x)
    if abs_x >= 1e9:
        return f"${x / 1e9:.1f}B"
    if abs_x >= 1e6:
        return f"${x / 1e6:.1f}M"
    if abs_x >= 1e3:
        return f"${x / 1e3:.1f}K"
    return f"${x:.0f}"


def get_metric(result: dict, key: str, default=None):
    """Back-compat: new schema has mean_npv/payback, old schema doesn't."""
    return result.get(key, default)


# ---------------------------------------------------------------------------
# Pages
# ---------------------------------------------------------------------------
def show_overview(scenarios_data, results_data, twin_data):
    st.header(f"Executive Summary - {twin_data['company_name']}")

    if not results_data:
        st.warning("No simulation results found. Run `python -m src.simulation.monte_carlo` to generate them.")
        return

    results = results_data["results"]
    top = max(results, key=lambda r: r["success_probability"])
    avg_roi = sum(r["mean_roi"] for r in results) / len(results)
    high_conf = sum(1 for r in results if r["success_probability"] > 0.85)
    has_npv = any("mean_npv" in r for r in results)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Best success probability", fmt_pct(top["success_probability"]), f"Scenario #{top['scenario_id']}")
    col2.metric("Avg ROI multiplier", f"{avg_roi:.1f}x", f"{len(results)} scenarios")
    col3.metric("High-confidence (>85%)", high_conf, f"{high_conf / len(results):.0%} of total")
    if has_npv:
        total_npv = sum(r.get("mean_npv", 0) for r in results)
        col4.metric("Avg NPV", fmt_money(total_npv / len(results)), "5-year horizon")
    else:
        col4.metric("Total simulations",
                    f"{results_data['simulation_parameters']['iterations'] * len(results):,}",
                    "Monte Carlo")

    st.markdown("---")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Success probability vs ROI")
        df = pd.DataFrame([
            {
                "Scenario": (r["scenario_name"][:35] + "...") if len(r["scenario_name"]) > 35 else r["scenario_name"],
                "Success probability": r["success_probability"],
                "ROI multiplier": r["mean_roi"],
                "Risk score": r.get("risk_score", 1 - r["success_probability"]),
            }
            for r in results
        ])
        fig = px.scatter(
            df, x="Success probability", y="ROI multiplier",
            color="Risk score", color_continuous_scale="RdYlGn_r",
            hover_data=["Scenario"],
            title="All scenarios - success vs return",
        )
        fig.update_layout(height=400)
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Top 10 by success probability")
        top10 = sorted(results, key=lambda r: r["success_probability"], reverse=True)[:10]
        top_df = pd.DataFrame([
            {
                "Scenario": (r["scenario_name"][:35] + "...") if len(r["scenario_name"]) > 35 else r["scenario_name"],
                "Success %": r["success_probability"] * 100,
                "ROI multiplier": r["mean_roi"],
            }
            for r in top10
        ])
        fig = px.bar(
            top_df, x="Success %", y="Scenario", orientation="h",
            color="ROI multiplier", color_continuous_scale="Blues",
            title="Success probability (%)",
        )
        fig.update_layout(height=400, showlegend=False, yaxis=dict(autorange="reversed"))
        st.plotly_chart(fig, use_container_width=True)


def show_top_scenarios(results_data, scenarios_data=None):
    st.header("TOP-3 Recommended Scenarios")
    if not results_data:
        st.warning("No simulation results available.")
        return

    results = results_data["results"]
    top_3 = sorted(results, key=lambda r: r["success_probability"], reverse=True)[:3]

    for i, scenario in enumerate(top_3, 1):
        with st.expander(f"RANK #{i}: {scenario['scenario_name']}", expanded=(i == 1)):
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Success probability", fmt_pct(scenario["success_probability"]))
            c2.metric("Mean ROI", f"{scenario['mean_roi']:.1f}x")
            mean_npv = get_metric(scenario, "mean_npv")
            c3.metric("Mean NPV", fmt_money(mean_npv) if mean_npv is not None else "-")
            payback = get_metric(scenario, "payback_years_median")
            c4.metric("Median payback", f"{payback:.1f}y" if payback is not None else "-")

            c1, c2, c3 = st.columns(3)
            c1.metric("90% CI lower", f"{scenario['confidence_90_lower']:.1f}x")
            c2.metric("90% CI upper", f"{scenario['confidence_90_upper']:.1f}x")
            c3.metric("Risk score", f"{scenario.get('risk_score', 1 - scenario['success_probability']):.3f}")

            # Recommendation banner
            p = scenario["success_probability"]
            if p >= 0.90:
                st.success("**STRONG RECOMMENDATION** - high success probability, proceed with confidence.")
            elif p >= 0.70:
                st.info("**PROCEED WITH CAUTION** - good odds, but requires risk management.")
            else:
                st.warning("**PILOT FIRST** - moderate success probability, test before scaling.")

            # Show which real cases informed this scenario, if available
            if scenarios_data:
                matching_scen = next(
                    (s for s in scenarios_data.get("scenarios", [])
                     if s.get("id") == scenario["scenario_id"]),
                    None,
                )
                if matching_scen and matching_scen.get("based_on_cases"):
                    cases = matching_scen["based_on_cases"]
                    prior = matching_scen.get("empirical_prior") or {}
                    failure_rate = prior.get("failure_rate")
                    rev_prior = (prior.get("revenue_uplift") or {})
                    n_cases = rev_prior.get("n", 0)
                    with st.container():
                        st.markdown("**Based on real cases (empirical prior):**")
                        st.markdown(", ".join(f"`{c}`" for c in cases[:5]))
                        cols = st.columns(3)
                        if failure_rate is not None:
                            cols[0].metric("Empirical failure rate", fmt_pct(failure_rate),
                                           f"n={n_cases} similar cases")
                        if rev_prior.get("p10") is not None:
                            cols[1].metric("Revenue uplift P10", fmt_pct(rev_prior["p10"]))
                            cols[2].metric("Revenue uplift P90", fmt_pct(rev_prior["p90"]))


def show_all_results(results_data):
    st.header("All Simulation Results")
    if not results_data:
        st.warning("No simulation results available.")
        return

    results = results_data["results"]
    has_npv = any("mean_npv" in r for r in results)

    rows = []
    for r in results:
        row = {
            "ID": r["scenario_id"],
            "Scenario": r["scenario_name"],
            "Success %": f"{r['success_probability'] * 100:.1f}",
            "Mean ROI x": f"{r['mean_roi']:.2f}",
            "Median ROI x": f"{r['median_roi']:.2f}",
            "90% CI Lower": f"{r['confidence_90_lower']:.2f}",
            "90% CI Upper": f"{r['confidence_90_upper']:.2f}",
            "Risk Score": f"{r.get('risk_score', 1 - r['success_probability']):.3f}",
        }
        if has_npv:
            row["Mean NPV ($M)"] = f"{r.get('mean_npv', 0) / 1e6:.2f}"
            row["Payback (y)"] = f"{r.get('payback_years_median', 0):.1f}"
        rows.append(row)

    df = pd.DataFrame(rows)
    st.dataframe(df, use_container_width=True, height=600)

    st.download_button(
        "Download as CSV",
        data=df.to_csv(index=False),
        file_name="timestone_simulation_results.csv",
        mime="text/csv",
    )


def show_compare(companies: dict, current_label: str):
    st.header("Compare Scenarios Side-by-Side")
    other_labels = [n for n in companies if n != current_label]
    if not other_labels:
        st.info("Need at least two companies with simulation results to compare.")
        return

    col1, col2 = st.columns(2)
    with col1:
        st.subheader(current_label)
        _, _, results_a = load_company_data(
            str(companies[current_label]["twin_path"]),
            str(companies[current_label]["scenarios_path"]) if companies[current_label]["scenarios_path"] else None,
            str(companies[current_label]["results_path"]) if companies[current_label]["results_path"] else None,
        )
        _render_compare_column(results_a)

    with col2:
        choice = st.selectbox("Compare with...", other_labels, key="compare_select")
        st.subheader(choice)
        _, _, results_b = load_company_data(
            str(companies[choice]["twin_path"]),
            str(companies[choice]["scenarios_path"]) if companies[choice]["scenarios_path"] else None,
            str(companies[choice]["results_path"]) if companies[choice]["results_path"] else None,
        )
        _render_compare_column(results_b)


def _render_compare_column(results_data):
    if not results_data:
        st.info("No simulation results for this company yet.")
        return
    results = results_data["results"]
    avg_p = sum(r["success_probability"] for r in results) / len(results)
    avg_roi = sum(r["mean_roi"] for r in results) / len(results)
    st.metric("Avg success probability", fmt_pct(avg_p))
    st.metric("Avg ROI multiplier", f"{avg_roi:.1f}x")
    top = sorted(results, key=lambda r: r["success_probability"], reverse=True)[:3]
    for r in top:
        st.markdown(f"**#{r['scenario_id']} {r['scenario_name']}** - P={fmt_pct(r['success_probability'])}, ROI={r['mean_roi']:.1f}x")


def show_methodology(results_data):
    st.header("Simulation Methodology")
    if not results_data:
        st.warning("No simulation results loaded.")
        return

    params = results_data["simulation_parameters"]
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("Monte Carlo parameters")
        st.code(f"""
Iterations per scenario : {params['iterations']:,}
Total scenarios         : {params['total_scenarios']}
Total simulations       : {params['iterations'] * params['total_scenarios']:,}
Horizon                 : {params.get('horizon_years', '?')}y
Discount rate           : {params.get('discount_rate', '?')}
Random seed             : {params['random_seed']}
        """)
        st.markdown("""
        ### Financial model
        - Capex paid in year 0
        - Benefits start after the implementation period
        - Adoption ramps up (40% / 70% / 95% / 100%)
        - `cost_reduction` applies to operating costs (not revenue)
        - NPV discounted at WACC (default 12%)
        """)

    with c2:
        st.subheader("Risk factors modeled")
        st.markdown("""
        - **Revenue variance** +/-15-40% per risk level (low/med/high)
        - **Cost variance** +/-10-35%
        - **Implementation delays** up to +80% for high-risk
        - **Cost overruns** up to +50%
        - **Market downturn** (8% prob, -30% revenue impact)
        - **Competitive response** (15% prob, -20% revenue impact)
        - **Execution failure** (5% prob, project lost)
        """)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    st.markdown('<h1 class="main-header">TimeStone AI</h1>', unsafe_allow_html=True)
    st.markdown('<p class="subtitle">Predict business transformation outcomes before you commit</p>', unsafe_allow_html=True)
    st.markdown("---")

    companies = discover_companies()
    if not companies:
        st.error("No twin files found in repo root. Run the digital twin generator first.")
        return

    with st.sidebar:
        st.markdown("### Company")
        company_label = st.selectbox("Select a company:", list(companies.keys()))
        twin_str = str(companies[company_label]["twin_path"])
        scen_str = str(companies[company_label]["scenarios_path"]) if companies[company_label]["scenarios_path"] else None
        res_str = str(companies[company_label]["results_path"]) if companies[company_label]["results_path"] else None
        twin, scenarios, results = load_company_data(twin_str, scen_str, res_str)

        st.info(
            f"**{twin.get('company_name', company_label)}**\n\n"
            f"Industry: {twin['metrics'].get('industry', '?')}\n\n"
            f"Revenue: {fmt_money(twin['metrics']['revenue'])}\n\n"
            f"Scenarios: {scenarios['total_scenarios'] if scenarios else '-'}\n\n"
            f"Simulations: {(results['simulation_parameters']['iterations'] * len(results['results'])) if results else '-'}"
        )

        st.markdown("### Navigation")
        page = st.radio("Select view:", [
            "Overview",
            "Top scenarios",
            "All results",
            "Sensitivity",
            "Compare companies",
            "Methodology",
        ])

    if page == "Overview":
        show_overview(scenarios, results, twin)
    elif page == "Top scenarios":
        show_top_scenarios(results, scenarios)
    elif page == "All results":
        show_all_results(results)
    elif page == "Sensitivity":
        show_sensitivity(scenarios, twin)
    elif page == "Compare companies":
        show_compare(companies, company_label)
    elif page == "Methodology":
        show_methodology(results)


def show_sensitivity(scenarios_data, twin_data):
    st.header("Sensitivity Analysis (Tornado Chart)")
    if not scenarios_data:
        st.warning("No scenarios available.")
        return
    st.markdown(
        "For the selected scenario, each input parameter is varied within a +/-30% band "
        "around its baseline. The bars below show how much the projected NPV swings. "
        "Wider bar -> that assumption is the most fragile."
    )

    scenarios = scenarios_data["scenarios"]
    labels = {f"#{s['id']} {s['name']}": s for s in scenarios[:200]}  # cap dropdown
    pick = st.selectbox("Pick a scenario:", list(labels.keys()))
    chosen = labels[pick]

    rev = twin_data["metrics"]["revenue"]
    op_costs = twin_data["metrics"]["operating_costs"]

    try:
        from timestone.services.sensitivity import sensitivity_analysis
    except ImportError:
        st.error("Sensitivity module unavailable.")
        return

    with st.spinner("Running sensitivity analysis (this takes ~5 seconds)..."):
        rows = sensitivity_analysis(chosen, rev, op_costs, iterations=400)

    if not rows:
        st.info("No sensitivity rows generated.")
        return

    baseline = rows[0].baseline_npv
    st.metric("Baseline NPV", fmt_money(baseline))

    # Build tornado chart
    df = pd.DataFrame([
        {
            "Parameter": r.parameter,
            "Low value NPV": r.low_npv,
            "High value NPV": r.high_npv,
            "Swing ($)": r.swing,
        }
        for r in rows
    ])
    fig = go.Figure()
    for _, row in df.iterrows():
        fig.add_trace(go.Bar(
            y=[row["Parameter"]],
            x=[row["High value NPV"] - baseline],
            base=baseline,
            orientation="h",
            name=f"{row['Parameter']} (high)",
            marker_color="#22c55e",
            showlegend=False,
        ))
        fig.add_trace(go.Bar(
            y=[row["Parameter"]],
            x=[row["Low value NPV"] - baseline],
            base=baseline,
            orientation="h",
            name=f"{row['Parameter']} (low)",
            marker_color="#ef4444",
            showlegend=False,
        ))
    fig.add_vline(x=baseline, line_dash="dash", line_color="black")
    fig.update_layout(
        title="NPV swing by parameter (green = upside, red = downside)",
        xaxis_title="NPV ($)",
        barmode="overlay",
        height=400,
        yaxis=dict(autorange="reversed"),
    )
    st.plotly_chart(fig, use_container_width=True)

    st.dataframe(df, use_container_width=True)


if __name__ == "__main__":
    main()
